#!/bin/bash

if [ -z "$OPENSHIFT_NODEJS_IP" ]; then
  echo "Running old Nodejs Cartridge";

  # Change home directory (bower puts a lot of cache and tmp directories here)
  HOME=$OPENSHIFT_REPO_DIR
  cd $OPENSHIFT_REPO_DIR

  # Cache npm components on main gear
  if [ "$OPENSHIFT_GEAR_UUID" == "$OPENSHIFT_APP_UUID" ]; then
    mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
    mkdir -p "$OPENSHIFT_DATA_DIR"bower_components

    ln -s "$OPENSHIFT_DATA_DIR"bower_components bower_components
    ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
  fi

  # install npm dependencies
  npm install

  # Prune unused node node_modules
  npm prune

fi;
